-- Migration 0003: Add user_profiles for persona-driven personalisation
--
-- Stores known data points for authenticated users (name, phone, company, etc.)
-- and an OpenAI-generated persona_summary that is injected into Dialogue context
-- at the start of each session so the agent can build rapport immediately.
--
-- Upsert logic (enforced at application level):
--   - Blank/null fields are filled in; existing values are never overwritten.
--   - persona_summary is regenerated by OpenAI whenever key fields change.
--
-- Run via:
--   wrangler d1 execute website-avatar-db --file=migrations/0003_add_user_profiles.sql --remote

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id            TEXT PRIMARY KEY,
  name               TEXT,
  phone              TEXT,
  company            TEXT,
  job_title          TEXT,
  persona_summary    TEXT,
  persona_updated_at INTEGER,
  created_at         INTEGER DEFAULT (unixepoch()),
  updated_at         INTEGER DEFAULT (unixepoch())
);
